spring.application.name=securedrop
# TEMP: Disable DB/JPA until Docker MySQL is added (remove in Phase 1)spring.autoconfigure.exclude=...
# //spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration