spring.application.name=securedrop

spring.datasource.url=jdbc:mysql://localhost:3307/securedrop
spring.datasource.username=securedrop_user
spring.datasource.password=securedrop_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
